### ISSUE TITLE
Export figures in HTML format

### ISSUE THREAD

**Issue by rodrigomoliveira1** [ross-rotordynamics/ross-report#8]
The current output from analysis.py file is a dictionary with several figures to include in the report.
Instead of if, we could use `fig.write_html("path\file_name.html")` command to export figure in HTML format to a local folder.

I know it could be an issue about running test and generating several html files. To this point, we could add a boolean argument `write_html` to `.run_report()` method. When running the report, set it to `True`. When just testing, set it to `False`.

What do you think, @GabrielBachmann @raphaeltimbo ?

**Comment by raphaeltimbo** [comment]
@rodrigomoliveira1 , regarding the testing part, I recommend using the tempfile module.
From it, you can import tempdir, which is the temporary directory for any operational system, and then you can create the necessary files there.

**Comment by GabrielBachmann** [comment]
At this moment, we don't need to generate any temp file.
All the plotly graphics are embeded in the output HTML and images can be included with the Image object, which converts jpg and svg image files in binary and includes it in a single HTML output.

**Comment by rodrigomoliveira1** [comment]
> At this moment, we don't need to generate any temp file.
> All the plotly graphics are embeded in the output HTML and images can be included with the Image object, which converts jpg and svg image files in binary and includes it in a single HTML output.

This solutions is working quite fine for awhile. I'm closing this issue. We can open this later.
